# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UrbanFlo
                                 A QGIS plugin
 This plugin runs computations on the phase 2 of Urban flo
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-08-05
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Kevin Kiprotich
        email                : kevinkiprotich0089@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox, QFileDialog
from qgis.core import QgsApplication

from .processing_provider.urban_flo_provider import UrbanFloProvider

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .urban_flo_dialog import UrbanFloDialog
import os.path
import pandas as pd


class UrbanFlo:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.provider = None
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'UrbanFlo_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&UrbanFlo')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    def initProcessing(self):
        self.provider = UrbanFloProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('UrbanFlo', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        self.initProcessing()
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/urban_flo/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Computes Averages and Totals'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&UrbanFlo'),
                action)
            self.iface.removeToolBarIcon(action)
        QgsApplication.processingRegistry().removeProvider(self.provider)

    def showErrorMessage(self,message):
        msg_box = QMessageBox()
        msg_box.setIcon(QMessageBox.Critical)
        msg_box.setWindowTitle("Error")
        msg_box.setText(message)
        msg_box.exec_()
    
    def getFolder(self, use):
        outputdir = QFileDialog.getExistingDirectory(None,"Select a folder","")
        if use == 'in':
            self.dlg.CSVFolderLineEdit.setText(outputdir)
        else:
            self.dlg.outputFolderLineEdit.setText(outputdir)
    
    def getSheet(self):
        options = QFileDialog.Options()
        filePath, _ = QFileDialog.getOpenFileName(
            None,
            "Select an Excel file",
            "",
            "Excel Files (*.xlsx *.xls);;All Files (*)",
            options=options
        )
        self.dlg.EvaluationsheetLineEdit.setText(filePath)

    def getSheetNames(self):
        if self.dlg.EvaluationSheetLineEdit.text() == "":
            return
        
        try:
            df = pd.read_excel(self.dlg.EvaluationSheetLineEdit.text())
            sheet_names = df.sheet_names
            self.dlg.SheetNameComboBox.clear()
            self.dlg.SheetNameComboBox.addItems(sheet_names)
        except Exception as e:
            self.showErrorMessage(f"Error reading Evaluation Sheet: {str(e)}")
            self.dlg.SheetNameComboBox.clear()

    
    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False
            self.dlg = UrbanFloDialog()
            self.dlg.CSVFolderPushButton.clicked.connect(lambda: self.getFolder('in'))
            self.dlg.EvaluationSheetPushButton.clicked.connect(self.getSheet)
            self.dlg.EvaluationSheetLineEdit.textChanged.connect(self.getSheetNames)
            self.dlg.OutputPushButton.clicked.connect(lambda: self.getFolder('out'))

        # show the dialog
        self.dlg.show()
        
